# Generated by Django 5.2.9 on 2026-06-25 00:42

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0134_owner'),
        ('netbox_wireless_circuits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WirelessGlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('global_tolerance_db', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tolerance_enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Wireless Global Settings',
                'verbose_name_plural': 'Wireless Global Settings',
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WirelessTargetException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('reason', models.TextField()),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('adjusted_rsl_dbm', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('suppress_alarms', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('wireless_license_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='netbox_wireless_circuits.wirelesslicenseprofile')),
            ],
            options={
                'verbose_name': 'Wireless Target Exception',
                'verbose_name_plural': 'Wireless Target Exceptions',
                'ordering': ('wireless_license_profile', '-effective_date'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
